version: '3.8'
services:
    node_app:
        container_name: node_container
        image: node_image
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
